# Generated by Django 5.0.6 on 2024-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenceprofil',
            name='profile_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenceprofil',
            name='profile_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenceprofil',
            name='profile_linked',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenceprofil',
            name='profile_twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
